### PR TITLE
Feature player pickup object

### PR DESCRIPTION
**Pull request by webthingee**
Card: https://trello.com/c/VNmRkC1o/15-picking-up-and-placing-items
Gif attached shows basic functionality.

Moved pickup code out of player controls
Added a selectionmanager that reports what is selectable (layer based)
That sends an action
Listeners like pickupmanager can respond
pickupmanager is on the held gameobject

Added colliders to the boxes so I could watch them fall when I dropped them. :)

### CODE REVIEW

**Comment by webthingee** [comment]
[Picking up and placing items](https://trello.com/c/VNmRkC1o/15-picking-up-and-placing-items)

**Review by Baradoros — CHANGES_REQUESTED** [review]
Needs some commenting in the code itself for when we inevitably have to add something last second and don't have time to figure it all out. Otherwise it looks sound.

**Comment by webthingee** [comment]
Added comments on the bigger script.
a little on the small one, it's pretty self commented.

on the Pickup script. I tried to use that nullable value stuff, but couldn't get it right.

```
Rigidbody heldRB = heldItem.GetComponent<Rigidbody>();
if (heldRB != null) heldRB.isKinematic = true;
```

How would you do this @Baradoros ? I really wanna use that nullable stuff you showed me :)

**Comment by Baradoros** [comment]
> Added comments on the bigger script.
> a little on the small one, it's pretty self commented.
> 
> on the Pickup script. I tried to use that nullable value stuff, but couldn't get it right.
> 
> ```
> Rigidbody heldRB = heldItem.GetComponent<Rigidbody>();
> if (heldRB != null) heldRB.isKinematic = true;
> ```
> How would you do this @Baradoros ? I really wanna use that nullable stuff you showed me :)

```
Rigidbody heldRB = heldItem.GetComponent<Rigidbody>();
heldRB?.isKinematic = true;
```
@webthingee

**Review by Baradoros — APPROVED** [review]

**Pull request merged**
